name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Docker
        run: docker --version

      - name: Install Dependencies
        run: npm install

      - name: Build and push Docker image

        run: |
          docker build -t 81quanghuy/videodemo:latest .
          docker login -u 81quanghuy -p huyvff@111
          docker push 81quanghuy/videodemo:latest
